# Generated by Django 2.0 on 2021-04-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(default='Role', max_length=100)),
                ('Email', models.EmailField(default='Email', max_length=100, unique=True)),
                ('Password', models.CharField(default='passwd', max_length=100)),
                ('Is_Created', models.DateTimeField(auto_now_add=True)),
                ('Is_Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('TimeIn', models.TimeField(auto_now_add=True)),
                ('TimeOut', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='fname', max_length=100)),
                ('Lastname', models.CharField(default='lname', max_length=100)),
                ('Gender', models.CharField(default='Gender', max_length=100)),
                ('Profilepic', models.ImageField(default='abc', upload_to='user-profile/')),
                ('Admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='fname', max_length=100)),
                ('Lastname', models.CharField(default='lname', max_length=100)),
                ('Gender', models.CharField(default='Gender', max_length=100)),
                ('Email', models.EmailField(default='Email', max_length=100, unique=True)),
                ('Password', models.CharField(default='passwd', max_length=100)),
                ('Profilepic', models.ImageField(default='abc', upload_to='seller-profile/')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
    ]
