# Generated by Django 2.0 on 2021-04-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Admin',
        ),
        migrations.AddField(
            model_name='faculty',
            name='Email',
            field=models.EmailField(default='Email', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Password',
            field=models.CharField(default='passwd', max_length=100),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
